<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.30.2" />


<title>England Premier 2016/17 (III) - Reviewing the data - R4football</title>
<meta property="og:title" content="England Premier 2016/17 (III) - Reviewing the data - R4football">



  








<link href='//cdn.bootcss.com/highlight.js/9.11.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/steviemac180">GitHub</a></li>
    
    <li><a href="https://twitter.com/steviemac180">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">4 min read</span>
    

    <h1 class="article-title">England Premier 2016/17 (III) - Reviewing the data</h1>

    
    <span class="article-date">2017/11/22</span>
    

    <div class="article-content">
      <p>We were going to move straight into looking at our variables but this morning i got a notification from <a href="https://www.r-bloggers.com/">rbloggers</a> with the latest R related posts including <a href="https://www.r-bloggers.com/xray-the-r-package-to-have-x-ray-vision-on-your-datasets/">this one</a> for a new package to do exactly what we were doing previously but in a different way. I decided to play about with our data with it. The goal is still to determine if we have any missing data, but with the xray package we can also do a bit more.</p>
<p>After installation (see linked article) run:</p>
<pre class="r"><code>library(xray)</code></pre>
<p>which will give us access to the xray functions</p>
<div id="check-for-missing-values-and-values-that-we-dont-want.." class="section level1">
<h1>Check for missing values and values that we don’t want..</h1>
<p>Use the xray::anomalies() function to look at our dataset as below:</p>
<pre class="r"><code>xray::anomalies(df.prem16_17.selected)</code></pre>
<pre><code>## Warning in xray::anomalies(df.prem16_17.selected): Found 3 possible problematic variables: 
## AR, HR, Div</code></pre>
<pre><code>## $variables
##    Variable   q qNA pNA qZero  pZero qBlank pBlank qInf pInf qDistinct
## 1        AR 380   0   -   360 94.74%      0      -    0    -         2
## 2        HR 380   0   -   360 94.74%      0      -    0    -         3
## 3      HTAG 380   0   -   232 61.05%      0      -    0    -         5
## 4      HTHG 380   0   -   193 50.79%      0      -    0    -         5
## 5      FTAG 380   0   -   131 34.47%      0      -    0    -         8
## 6      FTHG 380   0   -    83 21.84%      0      -    0    -         7
## 7        HY 380   0   -    67 17.63%      0      -    0    -         7
## 8        AY 380   0   -    61 16.05%      0      -    0    -         7
## 9       AST 380   0   -    12  3.16%      0      -    0    -        15
## 10       AC 380   0   -     5  1.32%      0      -    0    -        15
## 11       HC 380   0   -     5  1.32%      0      -    0    -        18
## 12      HST 380   0   -     4  1.05%      0      -    0    -        17
## 13      Div 380   0   -     0      -      0      -    0    -         1
## 14      FTR 380   0   -     0      -      0      -    0    -         3
## 15      HTR 380   0   -     0      -      0      -    0    -         3
## 16 HomeTeam 380   0   -     0      -      0      -    0    -        20
## 17 AwayTeam 380   0   -     0      -      0      -    0    -        20
## 18  Referee 380   0   -     0      -      0      -    0    -        20
## 19       HF 380   0   -     0      -      0      -    0    -        21
## 20       AF 380   0   -     0      -      0      -    0    -        21
## 21       AS 380   0   -     0      -      0      -    0    -        28
## 22       HS 380   0   -     0      -      0      -    0    -        33
## 23     Date 380   0   -     0      -      0      -    0    -       107
##         type anomalous_percent
## 1    Integer            94.74%
## 2    Integer            94.74%
## 3    Integer            61.05%
## 4    Integer            50.79%
## 5    Integer            34.47%
## 6    Integer            21.84%
## 7    Integer            17.63%
## 8    Integer            16.05%
## 9    Integer             3.16%
## 10   Integer             1.32%
## 11   Integer             1.32%
## 12   Integer             1.05%
## 13 Character                 -
## 14 Character                 -
## 15 Character                 -
## 16 Character                 -
## 17 Character                 -
## 18 Character                 -
## 19   Integer                 -
## 20   Integer                 -
## 21   Integer                 -
## 22   Integer                 -
## 23 Character                 -
## 
## $problem_variables
##   Variable   q qNA pNA qZero  pZero qBlank pBlank qInf pInf qDistinct
## 1       AR 380   0   -   360 94.74%      0      -    0    -         2
## 2       HR 380   0   -   360 94.74%      0      -    0    -         3
## 3      Div 380   0   -     0      -      0      -    0    -         1
##        type anomalous_percent                                 problems
## 1   Integer            94.74% Anomalies present in 94.74% of the rows.
## 2   Integer            94.74% Anomalies present in 94.74% of the rows.
## 3 Character                 -             Less than 2 distinct values.</code></pre>
<p>The output immediately alerts us to 3 potential problems in our data. We will look at this first</p>
</div>
<div id="ar---away-red-cards-hr---home-red-cards" class="section level1">
<h1>1. AR - Away red cards, HR - Home red cards</h1>
<p>This tells us we have 360 of our 380 observations as 0. This is not surprising as games don’t often have red cards so we accept this finding as being a feature of our data.</p>
</div>
<div id="div---division" class="section level1">
<h1>2. Div - Division</h1>
<p>This shows that there is only 1 distinct value throughut the entire variable describing the division. As we know this dataset to only be the English Premier League we are again happy with this.</p>
<p>We can, as before, see that we have no NA values.</p>
</div>
<div id="a-brief-look-at-distributions" class="section level1">
<h1>A Brief look at distributions</h1>
<p>We looked at our data briefly using the summary() function. We can again look at it using the xray package using the distributions() function. It leads nicely into what we are going to do next - investigating summary statistics of each variable.</p>
<pre class="r"><code>xray::distributions(df.prem16_17.selected)</code></pre>
<p>I haven’t shown the output here as it provides a lot of detailed information and i will do this individually for each variable in our data set starting with the dreaded “Date” variable……</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>



<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

